const songList = [
    {  //song1
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    },
    { //song2
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    },
    { //song3
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    },
    { //song4
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    },
    { //song5
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    },
    { //song6
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    },
    { //song7
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    },
    { //song8
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    },
    { //song9
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    },
    { //song10
        title: "title1", 
        artist: "artist1",
        album: "album1",
        src: "mp3", 
        songCover: "img1",
        desc: "lorem ipsum",
        rating: "5.0",
    }    
]